import type { Metadata } from "next";
import { Noto_Sans_Arabic } from "next/font/google";
import "./globals.css";
// import "@/assets/styles/style.css";
import { StoreProvider } from "./StoreProvider";
import Notification from "@/containers/Notification";
import "@/styles/core.scss";
import RouterHook from "./RouterHook";
import Menu from "@/views/Menu";
import SidebarRight from "@/views/SideBarRight";
const rubik = Noto_Sans_Arabic({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Q Twitter",
  description: "Generated by MeeM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={rubik.className}>
        <Notification />
        <StoreProvider>
          <RouterHook>
            <div className="layout flex justify-between">
              <Menu />
              {children}
              <SidebarRight />
            </div>
          </RouterHook>
        </StoreProvider>
      </body>
    </html>
  );
}
